LIST P = 16F887         
#INCLUDE "P16F887.INC"  

 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_OFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF  

;--------------------------VARIABLES------------------------------
CONTADOR  EQU 0x20     
;-------------------------------------------------------------------------------

;------------------------------RUTINA PRINCIPAL---------------------------------
        ORG 0x00
	GOTO INICIO
	ORG 0x04
	GOTO RUTINA_INTERRUPCION
	ORG 0x05

INICIO
	
        BSF STATUS,RP1    ; BANCO 3
        BSF STATUS,RP0   
	 
	CLRF ANSEL      ;CONFIGURO EL TRISA COMO I/O DIGITALES
	COMF ANSEL,1
	
	CLRF ANSELH      ;CONFIGURO EL TRISB COMO I/O DIGITALES
	COMF ANSELH,1
	
	;
	BCF STATUS,RP1    ;BANCO 1
        BSF STATUS,RP0    

	CLRF TRISA ; CONFIGURO EL TRISA COMO ENTRADA 
	COMF TRISA, 1 
	
	CLRF TRISD ; CONFIGURO EL PUERTO D COMO SALIDA PARA LOS DISPLAYS
	
	BCF STATUS,RP1    ;BANCO 0
        BCF STATUS,RP0  
	
	BCF ADCON0, CHS0; SELECCIONAMOS EL CANAL AN0 "0000"
	BCF ADCON0, CHS1
	BCF ADCON0, CHS2
	BCF ADCON0, CHS3
	BSF ADCON0, ADCS0  ; ELEGIMOS COMO FUENTE DE CLOCK FSOC/8
	BCF ADCON0, ADCS1
	BSF ADCON0, ADON

	
	MOVLW B'11111111' ; CARGAMOS TODO EN 1 PARA QUE ESTEN DESHABILITADOS LOS LEDS DE LOS DISPLAYS
	MOVWF PORTD
		
	BSF INTCON, 7     ;  GIE 
	BSF INTCON, 6     ;  PEIE HABILITAMOS INTERRUPCIONES PERIFERICAS

	
	BCF STATUS,RP1    ;BANCO 1
        BSF STATUS,RP0   
	
	BSF PIE1, ADIE ;  HABILITAMOS LA INTERRUPCION POR CONVERSION
	
	
	BCF STATUS,RP1    ;BANCO 0
        BCF STATUS,RP0
	
	BCF PIR1, ADIF ;  BAJAMOS LA BANDERA DE FIN DE CONVERSION 
	
	
	BCF STATUS,RP1    ;BANCO 1
        BSF STATUS,RP0 
	
	BCF ADCON1, ADFM ; ELEGIMOS GUARDAR LOS BITS MAS SIGNIFICATIVOS 
			 ; EN EL ADRESH
	BCF ADCON1, VCFG1 ; SELECCIONAMOS COMO VOLTAJE DE REFERENCIA VSS -  
	BCF ADCON1, VCFG0 ; SELECCIONAMOS COMO VOLTAJE DE REFERENCIA VDD +
	
	BCF STATUS,RP1    ; BANCO 0
        BCF STATUS,RP0
	
	MOVLW D'100' 
	MOVWF CONTADOR
	
		
BSF ADCON0, 1 ; PARA INICIAR LA CONVERSION  
	
NADA 
	GOTO NADA
	
	
	
RUTINA_INTERRUPCION
		
	COMF ADRESH,0 ; COMPLEMENTAMOS POR QUE USAMOS LOGICA NEGATIVA EN LOS DISPLAYS
		      ; Y GUARDAMOS EN W
	MOVWF PORTD ; VISUALIZAMOS EN PORTD
        BCF PIR1, ADIF ; BAJAMOS BANDERA DE INTERRUPCION ANTES DE SALIR	
	CALL RETARDO
        BSF ADCON0, 1 ; PARA INICIAR LA CONVERSION
RETFIE

RETARDO ; HACEMOS UN RETARDO  DE 20uS
	
DECFSZ CONTADOR,1
GOTO RETARDO
MOVLW D'100' 
MOVWF CONTADOR
RETURN
	
	END
	
	
	
	
	
	
	
	
	
	
	
	